version: '3.7'
services:
    web:
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./:/srv/html/geo
        ports:
          - 8000:8000

        env_file:
            - ./.env.dev
        depends_on:
            - db

        networks:
            - geo

    db:
        image: postgis/postgis:15-3.3
        container_name: postgis
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "gis_db"
            POSTGRES_USER: "gis_user"
            POSTGRES_PASSWORD: "gis_user"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./:/var/lib/postgresql/data

        networks:
            - geo

networks:
  geo:
    driver: bridge